### PR TITLE
Add 2023-2024 Ford Escape (CAN-FD)

### PR DESCRIPTION
**Pull request by northportio**
I believe I have added all the necessary info to add my 2023 Escape. It seems that as of May 12, 2024, #4 seems to be a Ford platform issue rather than a model specific issue. 

Requesting someone review my addition before merging as this is my first car port.

### CODE REVIEW

**Comment by northportio** [comment]
I've verified that this addition functions just the same as manually setting sunnypilot/bluepilot to a 2021 Mach E but with the vehicle being autodetected.

Vehicle Used for testing: 2023 Ford Escape HEV AWD

Request to merge

**Comment by alan-polk** [comment]
Can you please post a public route where you have driven with this PR so we can review the logs?

**Comment by northportio** [comment]
`56574443e0c3783c/2024-05-20--12-52-40`

**Comment by alan-polk** [comment]
Review by Anthony, approved to merge.

**Pull request merged**
