### PR TITLE
Added Support for TSR for CAN vehicles.

### PR DESCRIPTION
**Pull request by jasco113**
in carstate.py I removed the if's that were preventing the Traffic Sign Recognition (TSR) signals from being passed into to the comma for use in Speed limit control.  
This has been tested with 2024 Ford Maverick and is working.
Note:  Maverick does not have TSR enabled from factory and was added to my vehicle using Forscan.

Will need to confirm behavior with vehicles that have not had the feature enabled via Forscan to see if the signal still exists.

### CODE REVIEW

**Comment by Camry2731** [comment]
If I recall Q3 vehicles that didn't have TSR enabled did have issues with the signals being passed. However, and I don't have it on hand currently, there is a way to check to see if the vehicle has the feature present by checking the vehicle for a specific value. Assuming the issue above is the case, then an if check should be implemented to determine if the vehicle has the feature enabled and if so allow TSR to work. I'll provide the specifics when I get a chance (I could be wrong but this is what I remember)

**Comment by blue-genie** [comment]
@jasco113 - please make sure that your branch you are using for this PR is based on [BluePilotDev:experimental](https://github.com/BluePilotDev/bluepilot/tree/experimental) 

Currently the PR shows:
image

I don't think you changed this many files. This is because your base is based on another branch not on experimental, or you should change the PR to point to the base branch that you use.

Now about your change:

Comma published some sanitized routes online, for everybody to use for testing, I modified one of their python scripts to look through all the FORD models that the publish and see which ones have `cp0.vl["Traffic_RecognitnData"]["TsrVLim1MsgTxt_D_Rq"]`. This is the output:

```
seen - Got 287 segments for platform FORD_BRONCO_SPORT_MK1, sampling 5 segments
seen - Not Found Message
seen - Got 137 segments for platform FORD_ESCAPE_MK4, sampling 5 segments
seen - Found Message
seen - Got 1041 segments for platform FORD_EXPLORER_MK6, sampling 5 segments
seen - Not Found Message
seen - Got 5 segments for platform FORD_F_150_MK14, sampling 5 segments
seen - Found Message
seen - Got 3 segments for platform FORD_F_150_LIGHTNING_MK1, sampling 3 segments
seen - Found Message
seen - Got 56 segments for platform FORD_FOCUS_MK4, sampling 5 segments
seen - Not Found Message
seen - Got 637 segments for platform FORD_MAVERICK_MK1, sampling 5 segments
seen - Not Found Message
seen - Got 3 segments for platform FORD_MUSTANG_MACH_E_MK1, sampling 3 segments
seen - Found Message
Skipping platform: FORD_RANGER_MK2, no data available
```

As you see ONLY CAN-FD cars send that message by default.

The problem is that the cars that don't send this message cause the following error `opendbc/can/parser.cc: 0x3CD 'Traffic_RecognitnData' NOT SEEN` or `opendbc/can/parser.cc: 0x3CD 'Traffic_RecognitnData' TIMED OUT` . I understand that some CAN cars send that message, but you need to find the flag that keeps track of the TSR feature and remove the `if` statement only for those cars.

Until the `if` condition is carefully adjusted I'm not in favor of changing the `if` statement, this is why I added the `if` statement when I provided the code change to SP team.

BTW - I'm the one who found the nee and way to send the TSR info to the UI in SP, then i created a PR and SP team merged it.

**Comment by Camry2731** [comment]
Sorry it took so long to get back with you. So below is the block id, offset, and bitmask for TSR

```
  ipma_traffic_sign_recognition = VehicleSetting(
    comment='Traffic Sign Recognition',
    ecu=(FordEcu.ImageProcessingModuleA, FordPart.IPMA_Q3),
    block_id=1,
    offset=3,
    bit_mask=0x10,
    value_map={
      0x0: 'Off',
      0x1: 'On',
```

We should be able to reuse code that's used currently to detect the presence of TJA and LKA

```
      # Lock out if the car does not have needed lateral and longitudinal control APIs.
      # Note that we also check CAN for adaptive cruise, but no known signal for LCA exists
      pscm_config = next((fw for fw in car_fw if fw.ecu == Ecu.eps and b'\x22\xDE\x01' in fw.request), None)
      if pscm_config:
        if len(pscm_config.response) != 24:
          ret.dashcamOnly = True
        else:
          config_tja = pscm_config.response[7]  # Traffic Jam Assist
          config_lca = pscm_config.response[8]  # Lane Centering Assist
          if config_tja != 0xFF or config_lca != 0xFF:
            ret.dashcamOnly = True
```

Using that above and adapting it, it *should* be this:

```
  # DE00 corresponds to block 1
  pscm_config = next((fw for fw in car_fw if fw.ecu == Ecu.eps and b'\x22\xDE\x00' in fw.request), None)
  if pscm_config:
    if len(pscm_config.response) != 24:
      ret.dashcamOnly = True
    else:
      # Check the status of Traffic Sign Recognition at offset 3 with bit mask 0x10
      config_tsr = pscm_config.response[3] & 0x10
      
      # If Traffic Sign Recognition is enabled (bit is 1), allow the signal to pass
      if config_tsr == 0x1:
        ret.cruiseState.speedLimit = self.update_traffic_signals(cp_cam)
```

**Comment by zhenglishan** [comment]
The 2020 Escape successfully tested traffic sign recognition.

**Pull request closed without merging**
